In [1]:
import torch

In [2]:
x = torch.empty(5, 3)

In [3]:
print(x)
print(x.dtype)

tensor([[1.8361e+25, 1.4603e-19, 6.4069e+02],
        [2.7489e+20, 1.5444e+25, 1.6217e-19],
        [7.0062e+22, 1.6795e+08, 4.7423e+30],
        [4.7393e+30, 9.5461e-01, 4.4377e+27],
        [1.7975e+19, 4.6894e+27, 7.9463e+08]])
torch.float32


In [4]:
y = torch.rand(5, 3)
print(y)
print(y.dtype)

tensor([[0.6686, 0.3887, 0.9002],
        [0.2236, 0.0437, 0.2024],
        [0.2876, 0.0108, 0.7146],
        [0.1709, 0.2864, 0.0155],
        [0.8747, 0.2825, 0.0401]])
torch.float32


In [5]:
print(x - y)

tensor([[ 1.8361e+25, -3.8871e-01,  6.3979e+02],
        [ 2.7489e+20,  1.5444e+25, -2.0238e-01],
        [ 7.0062e+22,  1.6795e+08,  4.7423e+30],
        [ 4.7393e+30,  6.6820e-01,  4.4377e+27],
        [ 1.7975e+19,  4.6894e+27,  7.9463e+08]])


In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
y = torch.zeros(5, 3, dtype=torch.float64)
print(x)
print(y)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [7]:
x = torch.tensor([5.5, 3])
print(x)
print(x.shape)

tensor([5.5000, 3.0000])
torch.Size([2])


In [8]:
x = x.new_ones(5, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [9]:
x = x.new_ones(5, 3, dtype=torch.float32)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [10]:
print(x.dtype)

torch.float32


In [11]:
print(x.shape)
print(x.size())

torch.Size([5, 3])
torch.Size([5, 3])


In [12]:
a = torch.Tensor(5, 3)

In [13]:
a

tensor([[-5.5879e-09,  4.5822e-41,  4.6534e+33],
        [ 7.5615e+28,  6.8292e+22,  7.5654e+28],
        [ 6.8292e+22,  5.7453e-44,  4.6243e-44],
        [ 0.0000e+00,  3.9236e-44,  0.0000e+00],
        [-5.5968e-09,  4.5822e-41,  4.6534e+33]])

In [14]:
print(a.dtype)

torch.float32


In [15]:
x = torch.ones(5, 3)
print(x.dtype)
y = torch.ones(5, 3, dtype=torch.float)
print(y)
print(y.dtype)

torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [16]:
z = torch.ones(5, 3, dtype=torch.long)
print(z)
print(z.dtype)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
torch.int64


In [17]:
x = torch.arange(10, 20, 2)
print(x)

tensor([10, 12, 14, 16, 18])


In [18]:
x = torch.arange(10, 20)
print(x)

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])


In [19]:
l = [0, 1, 2, 3, 4]

In [20]:
print(l[0:4])

[0, 1, 2, 3]


In [21]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x)
print(y)
result = torch.rand(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.6712, 0.5153, 0.4019],
        [0.3320, 0.7969, 0.7156],
        [0.2807, 0.1268, 0.2976],
        [0.2092, 0.0603, 0.6276],
        [0.7202, 0.8279, 0.4095]])
tensor([[0.5436, 0.7570, 0.2570],
        [0.2338, 0.3410, 0.6300],
        [0.7332, 0.7594, 0.9113],
        [0.9311, 0.6034, 0.4129],
        [0.5250, 0.2563, 0.5579]])
tensor([[1.2148, 1.2723, 0.6589],
        [0.5658, 1.1379, 1.3456],
        [1.0139, 0.8862, 1.2089],
        [1.1403, 0.6637, 1.0405],
        [1.2452, 1.0843, 0.9674]])


In [22]:
x.copy_(y)

tensor([[0.5436, 0.7570, 0.2570],
        [0.2338, 0.3410, 0.6300],
        [0.7332, 0.7594, 0.9113],
        [0.9311, 0.6034, 0.4129],
        [0.5250, 0.2563, 0.5579]])

In [23]:
x

tensor([[0.5436, 0.7570, 0.2570],
        [0.2338, 0.3410, 0.6300],
        [0.7332, 0.7594, 0.9113],
        [0.9311, 0.6034, 0.4129],
        [0.5250, 0.2563, 0.5579]])

In [24]:
x.add_(y)

tensor([[1.0872, 1.5141, 0.5140],
        [0.4676, 0.6819, 1.2599],
        [1.4665, 1.5188, 1.8227],
        [1.8623, 1.2067, 0.8258],
        [1.0500, 0.5127, 1.1158]])

In [30]:
x.reshape(1, -1)

tensor([[0.1238, 0.7436, 0.4771, 1.3945, 0.3195, 1.1529, 1.4949, 0.4444, 0.4927,
         0.1228, 1.0980, 0.4004, 1.4010, 0.3762, 0.7925]])

In [32]:
x.view(1, -1)

tensor([[0.1238, 0.7436, 0.4771, 1.3945, 0.3195, 1.1529, 1.4949, 0.4444, 0.4927,
         0.1228, 1.0980, 0.4004, 1.4010, 0.3762, 0.7925]])

In [33]:
x = torch.arange(12)
y = torch.arange(12)
z = x.view(3, 4)
m = x.reshape(3, 4)
print(x)
print(y)
print(z)
print(m)
z.add_(2)
print(x)
print(y)
print(z)
print(m)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]])
tensor([[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]])


In [34]:
x = torch.arange(12)
y = x.reshape(3, 4)
y = y + 1
print(x)
print(y)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [60]:
x = torch.arange(12)
y = x.clone().view(3, 4)
y.add_(1)
print(x)
print(y)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [41]:
x = torch.arange(12)
y = x.view(3, 4)
x += 1
print(x)
print(y)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [42]:
x = torch.arange(12)
y = x.reshape(3, 4)
x += 1
print(x)
print(y)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [63]:
x = torch.rand(3, 3)
print(x)
print(x.diag(),x.diag().shape)

tensor([[0.0555, 0.4850, 0.5954],
        [0.2176, 0.9366, 0.2764],
        [0.8673, 0.7038, 0.7404]])
tensor([0.0555, 0.9366, 0.7404]) torch.Size([3])


In [64]:
print(x.triu())

tensor([[0.0555, 0.4850, 0.5954],
        [0.0000, 0.9366, 0.2764],
        [0.0000, 0.0000, 0.7404]])


In [65]:
x

tensor([[0.0555, 0.4850, 0.5954],
        [0.2176, 0.9366, 0.2764],
        [0.8673, 0.7038, 0.7404]])

In [66]:
x.t_()

tensor([[0.0555, 0.2176, 0.8673],
        [0.4850, 0.9366, 0.7038],
        [0.5954, 0.2764, 0.7404]])

In [67]:
x

tensor([[0.0555, 0.2176, 0.8673],
        [0.4850, 0.9366, 0.7038],
        [0.5954, 0.2764, 0.7404]])

In [71]:
x = torch.arange(6).view(2, 3)
y = torch.arange(3).view(1, 3)
z = torch.arange(3)

In [72]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [76]:
print(y)
x + y

tensor([[0, 1, 2]])


tensor([[0, 2, 4],
        [3, 5, 7]])

In [78]:
x = torch.arange(1, 3).view(1, 2)
y = torch.arange(1, 4).view(3, 1)
print(x)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [79]:
x = torch.randn(2, 3)
print(id(x))
x += 1
print(id(x))
x = x + 1
print(id(x))

140516598150144
140516598150144
140516598344512


In [81]:
a = torch.ones(2, 2)

In [82]:
a

tensor([[1., 1.],
        [1., 1.]])

In [83]:
import numpy as np
b = a.numpy()
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
[[1. 1.]
 [1. 1.]]


In [84]:
a += 1
print(b)
b += 1
print(a)

[[2. 2.]
 [2. 2.]]
tensor([[3., 3.],
        [3., 3.]])


In [85]:
c = torch.from_numpy(b)
print(c)

tensor([[3., 3.],
        [3., 3.]])


In [91]:
device = torch.device('cpu')

In [92]:
device

device(type='cpu')

In [25]:
x = torch.ones(2, 2, requires_grad=True)

In [26]:
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [28]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [29]:
print(x.is_leaf, y.is_leaf)

True False


In [33]:
z = torch.ones(2, 2)
print(x.requires_grad)
print(y.requires_grad)
print(z.requires_grad)

True
True
False


In [43]:
z = y * y * 3
out = z.mean()
print(z, out)
print(z.requires_grad)
print(z.grad_fn)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
True


In [42]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a)
print(b.sum(axis=1))
b = (a * a).sum()
print(b.grad_fn)

False
True
tensor([9.4101e+03, 1.9037e+00], grad_fn=<SumBackward1>)


In [45]:
out.backward()

In [46]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [47]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [48]:
out2 = x.sum()
out2.backward()
print(x.grad)

out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])
tensor([[1., 1.],
        [1., 1.]])


In [54]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)
y = 2 * x
z = y.view(2, 2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)


In [56]:
v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
z.backward(v)
print(x.grad)

tensor([2.0000, 0.2000, 0.0200, 0.0020])


In [89]:
x = torch.tensor(1.0, requires_grad=True)
y1 = x ** 2
with torch.no_grad():
    y2 = x ** 3
y3 = y1 + y2

print(x.requires_grad)
print(y1, y1.requires_grad)
print(y2, y2.requires_grad)
print(y3, y3.requires_grad)

True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [93]:
x.grad.data.zero_()
y1.backward(retain_graph=True)
y3.backward(retain_graph=True)

print(x.grad)

tensor(4.)


In [62]:
x = torch.ones(1, requires_grad=True)

print(x.data)
print(x.data.requires_grad)

y = 2 * x
x.data *= 100
y.backward()
print(x)
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])


tensor(0.)